# Analysing the coverage of individual attributes

## A function to establish the DB connection

In [1]:
import os

import psycopg2


def getConnection():
    # Connect to postgres with a copy of the MIMIC-III database
    con = psycopg2.connect(
        dbname='omop_migration_etl_20250416',
        user=os.environ['POSTGRES_USER_NAME'],
        host=os.environ['POSTGRES_HOSTNAME'],
        port=os.environ['POSTGRES_PORT_NUMBER'],
        password=os.environ['POSTGRES_PASSWORD']
        )
    return con

## Coverage analysis for vitals

In [4]:
import pandas as pd


con = getConnection()

coverageQuery = '''
    select
        con.concept_name,
        con.concept_code,
        (count(distinct mmt.person_id)::float * 100)/(select count(distinct(person_id)) from omop_migration_etl_20250416.cdm_measurement) as person_level_coverage,
        (count(distinct mmt.visit_occurrence_id)::float * 100)/(select count(distinct(visit_occurrence_id)) from omop_migration_etl_20250416.cdm_measurement) as episode_level_coverage
    from
        omop_migration_etl_20250416.cdm_measurement mmt
    inner join omop_migration_etl_20250416.concept con
        on con.concept_code = mmt.measurement_concept_id
    where
        mmt.unit_id = 'chartevents'
    group by
        con.concept_name, con.concept_code
    order by
        episode_level_coverage desc
    ;
'''

coverageDf = pd.read_sql_query(coverageQuery, con)
coverageDf

/tmp/ipykernel_155964/3189846400.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  coverageDf = pd.read_sql_query(coverageQuery, con)

,concept_name,concept_code,person_level_coverage,episode_level_coverage
0,Systolic blood pressure,271649006,79.559387,46.205586
1,Diastolic blood pressure,271650006,79.482759,46.148807
2,Peripheral oxygen saturation,431314004,80.498084,45.738246
3,Temperature,246508008,78.927203,43.665786
4,Respiratory rate,86290005,78.850575,43.602455
5,Mean blood pressure,6797001,77.796935,37.786901
6,Heart rate,364075005,67.605364,36.070407
7,Peripheral pulse,54718008,78.237548,29.263392
8,Body weight,27113001,68.850575,24.109541
9,Oxygen,24099007,58.888889,16.267389
10,Body mass index,60621009,56.264368,14.367452
11,Inspired oxygen concentration,250774007,47.567050,8.442707
12,Oral temperature,415945006,31.858238,5.811186
13,Invasive systolic arterial pressure,251071003,26.877395,3.614247
14,Invasive diastolic arterial pressure,251073000,26.800766,3.603328
15,Central venous pressure,71420008,8.754789,1.061344
16,Urinary bladder structure,89837001,7.567050,0.875718
17,Intravascular,261101003,1.762452,0.205281
18,Intracranial pressure,250844005,1.168582,0.133214
19,Cerebral perfusion pressure,250846007,1.091954,0.124479
20,Temperature of skin,364537001,0.287356,0.032758
21,Brain structure,12738006,0.191571,0.021838

## Coverage analysis for labs

In [5]:
import pandas as pd


con = getConnection()

coverageQuery = '''
    select
        con.concept_name,
        con.concept_code,
        (count(distinct mmt.person_id)::float * 100)/(select count(distinct(person_id)) from omop_migration_etl_20250416.cdm_measurement) as person_level_coverage,
        (count(distinct mmt.visit_occurrence_id)::float * 100)/(select count(distinct(visit_occurrence_id)) from omop_migration_etl_20250416.cdm_measurement) as episode_level_coverage
    from
        omop_migration_etl_20250416.cdm_measurement mmt
    inner join omop_migration_etl_20250416.concept con
        on con.concept_code = mmt.measurement_concept_id
    where
        mmt.unit_id = 'labevents'
    group by
        con.concept_name, con.concept_code
    order by
        episode_level_coverage desc
    ;
'''

coverageDf = pd.read_sql_query(coverageQuery, con)
coverageDf

/tmp/ipykernel_155964/2210091202.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  coverageDf = pd.read_sql_query(coverageQuery, con)

,concept_name,concept_code,person_level_coverage,episode_level_coverage
0,Haemoglobin estimation,1022431000000105,99.923372,79.568037
1,Eosinophil count,71960002,99.885057,78.642091
2,Monocyte,55918008,99.885057,78.609334
3,Lymphocyte,56972008,99.885057,78.602782
4,Red blood cell count,14089001,99.904215,78.423708
5,Hematocrit,165418001,99.904215,78.423708
6,MCHC - Mean corpuscular haemoglobin concentration,1022481000000109,99.904215,78.421524
7,MCH - Mean corpuscular haemoglobin,1022471000000107,99.904215,78.421524
8,MCV - Mean corpuscular volume,1022491000000106,99.904215,78.417156
9,Red blood cell distribution width,993501000000105,99.904215,78.366928
10,White blood cell count,767002,99.885057,78.358193
11,Basophil count,1022571000000108,99.885057,78.227163
12,Neutrophil count,30630007,99.885057,78.183486
13,Platelet,16378004,99.693487,78.120155
14,Chloride salt,50213009,99.770115,77.593850
15,Sodium,39972003,99.731801,77.554541
16,Potassium,88480006,99.731801,76.964906
17,Creatinine,15373003,99.770115,76.866633
18,Blood urea,1028281000000106,99.770115,76.591470
19,Bicarbonate,68615006,99.770115,76.549977
20,Albumin,52454007,98.122605,69.692734
21,Total alkaline phosphatase level,997611000000101,98.122605,69.511476
22,GGT (gamma-glutamyl transferase) level,1028091000000102,98.103448,69.498373
23,Total protein measurement,304383000,98.045977,69.245048
24,Alanine aminotransferase,56935002,97.854406,69.155511
25,Globulin,81905004,98.045977,68.987356
26,Bilirubin,79706000,97.892720,68.225197
27,Calcium,5540006,94.789272,64.514861
28,Phosphate measurement,104866001,94.674330,63.947064
29,Magnesium measurement,38151008,94.789272,63.905571
30,Estimated glomerular filtration rate by labora...,1107411000000104,85.153257,54.220262
31,Corrected measurement of calcium,443796007,75.842912,47.033260
32,Prothrombin time,852471000000107,86.666667,37.692996
33,International normalized ratio derived warfari...,439814009,86.647510,37.682077
34,Elevated C-reactive protein,119971000119104,96.321839,35.886965
35,"Partial thromboplastin time, activated",42525009,86.436782,35.871678
36,Fibrinogen measurement,250346004,83.773946,33.288201
37,Thrombin time,1015431000000108,83.352490,31.082527
38,Glucose level - finding,365811003,87.413793,25.795462
39,Urine pH test,167305006,86.494253,22.984866
40,Erythrocyte,41898006,84.750958,21.820882
41,Leukocyte,52501007,81.360153,20.735516
42,Serum ionized calcium (pH 7.4) level,1013241000000102,74.885057,16.763119
43,Cord venous blood partial pressure of oxygen,791921000000101,74.061303,16.295779
44,Calculus carbonate content,1024181000000106,74.099617,16.249918
45,Hemoglobin saturation with oxygen,103228002,73.984674,16.249918
46,Glucose,67079006,74.118774,16.247734
47,Arterial partial pressure of carbon dioxide,144272005,74.099617,16.241183
48,Carbohydrate level,1032081000000104,74.080460,16.236815
49,Fluid sample pH,1024211000000107,74.080460,16.236815
50,Lactate,83036002,73.888889,16.040270
51,Base excess,129907001,57.260536,10.626542